In [325]:
# importing padas
import pandas as pd

In [326]:
# importing file 
data = pd.read_csv("spotify_noisy.csv")
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,hiphop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,other
3,2023-09-03,27,august,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,pop
4,2023-12-26,31,Please Come Home for Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-12-27,2,Last Christmas - Single Version,Wham!,87,270295,Album,16,2023-07-07,False,NaN,https://open.spotify.com/search/Last%20Christm...,other
39996,2024-02-20,28,QLONA,KAROL G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,other
39997,2023-06-05,20,PRC,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,other
39998,2024-02-17,26,LA FALDA,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,other
39999,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,other

In [327]:
# Know about shape and column
data.shape

(40000, 13)

In [328]:
# column name 
data.columns

Index(['date', 'position', 'song', 'artist', 'popularity', 'duration_ms',
       'album_type', 'total_tracks', 'release_date', 'is_explicit',
       'album_cover_url', 'link', 'genre'],
      dtype='object')

In [329]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             40000 non-null  object
 1   position         40000 non-null  int64
 2   song             40000 non-null  object
 3   artist           40000 non-null  object
 4   popularity       40000 non-null  int64
 5   duration_ms      40000 non-null  int64
 6   album_type       40000 non-null  object
 7   total_tracks     40000 non-null  int64
 8   release_date     39502 non-null  object
 9   is_explicit      40000 non-null  bool
 10  album_cover_url  38971 non-null  object
 11  link             39433 non-null  object
 12  genre            40000 non-null  object
dtypes: bool(1), int64(4), object(8)
memory usage: 3.7+ MB

# Column-wise Cleaning

# Date Column

In [330]:
df = data["date"]
df

0        2023-10-18
1        2023-07-02
2        2024-07-04
3        2023-09-03
4        2023-12-26
            ...
39995    2023-12-27
39996    2024-02-20
39997    2023-06-05
39998    2024-02-17
39999    2023-12-18
Name: date, Length: 40000, dtype: object

In [331]:
# Null value 
df.isnull().sum()

np.int64(0)

In [332]:
# data type
df.dtype

dtype('O')

In [333]:
# converting into date
df = pd.to_datetime(data['date'], errors='coerce')

In [334]:
# # Null value 
df.isnull().sum()

np.int64(0)

In [335]:
# data type
df.dtype

dtype('<M8[ns]')

In [336]:
# getting minimum value
df.min()

Timestamp('2023-05-18 00:00:00')

In [337]:
# getting maximum value
df.max()

Timestamp('2024-11-27 00:00:00')

In [338]:
data["date"] = df

In [339]:
# all done

# Position

In [340]:
df = data["position"]
df

0        20
1        12
2        22
3        27
4        31
         ..
39995     2
39996    28
39997    20
39998    26
39999    43
Name: position, Length: 40000, dtype: int64

In [341]:
# statistical summary
df.describe()

count    40000.000000
mean        25.515400
std         14.461421
min          1.000000
25%         13.000000
50%         26.000000
75%         38.000000
max         55.000000
Name: position, dtype: float64

In [342]:
# Converting to numeric
df = pd.to_numeric(data['position'], errors='coerce')

In [343]:
# null value
df.isnull().sum()

np.int64(0)

In [344]:
# converting as integer
df = df.astype(int)

In [345]:
data["position"] = df

In [346]:
# more than 50
data[data["position"]>50].count()

date               164
position           164
song               164
artist             164
popularity         164
duration_ms        164
album_type         164
total_tracks       164
release_date       153
is_explicit        164
album_cover_url    150
link               161
genre              164
dtype: int64

In [347]:
# removing more than 50 or less
data = data[(data['position'] > 0) & (data['position'] <= 50)]

In [348]:
# counting data
data.count()

date               39836
position           39836
song               39836
artist             39836
popularity         39836
duration_ms        39836
album_type         39836
total_tracks       39836
release_date       39349
is_explicit        39836
album_cover_url    38821
link               39272
genre              39836
dtype: int64

In [349]:
# all done

# Song

In [350]:
df =  data["song"]
df

0                                               vampire
1                                         Suicide Doors
2                                             As It Was
3                                                august
4        Please Come Home for Christmas - 2013 Remaster
                              ...
39995                   Last Christmas - Single Version
39996                                             QLONA
39997                                               PRC
39998                                          LA FALDA
39999                                        La Víctima
Name: song, Length: 39836, dtype: object

In [351]:
# data type
df.dtype

dtype('O')

In [352]:
# null value 
df.isnull().sum()

np.int64(0)

In [353]:
# captalization
df = df.str.title()

In [354]:
# removing extra space
df = df.str.strip()

In [355]:
# null value 
df.isnull().sum()

np.int64(0)

In [356]:
# removing unwanted space from middle
df= df.str.replace(r'\s+', ' ', regex=True)

In [357]:
data["song"] = df

C:\Users\sidha\AppData\Local\Temp\ipykernel_10848\1634394428.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["song"] = df

In [358]:
# all done

# Artist

In [359]:
df = data["artist"]
df

0                    Olivia Rodrigo
1                      Lil Uzi Vert
2                      Harry Styles
3                      Taylor Swift
4                            Eagles
                    ...
39995                         Wham!
39996                       KAROL G
39997    Peso Pluma & Natanael Cano
39998                   Myke Towers
39999                          Xavi
Name: artist, Length: 39836, dtype: object

In [360]:
# data type
df.dtype

dtype('O')

In [361]:
# null value 
df.isnull().sum()

np.int64(0)

In [362]:
# removing extra space
df = df.str.strip()

In [363]:
# double space in middle 
df = df.str.replace(r'\s+', ' ', regex=True)

In [364]:
# titlization
df = df.str.title()

In [365]:
# name contain useless char
df[df.str.contains(r'[^a-zA-Z\s,.-]', regex=True, na=False)]

14                        Hanumankind & Kalmi
23                 Grupo Frontera & Bad Bunny
25                              Michael Bublé
27              Luis R Conriquez & Neton Vega
38                      Bizarrap & Peso Pluma
                         ...
39990                       Jung Kook & Latto
39991    The Weeknd & Jennie & Lily-Rose Depp
39994               David Guetta & Bebe Rexha
39995                                   Wham!
39997              Peso Pluma & Natanael Cano
Name: artist, Length: 7207, dtype: object

In [366]:
df[df.str.contains(r'[^a-zA-Z\s,.-]', regex=True, na=False)].count()

np.int64(7207)

In [367]:
data["artist"] = df

C:\Users\sidha\AppData\Local\Temp\ipykernel_10848\3282266856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["artist"] = df

In [368]:
# all done

# Popularity

In [369]:
df = data["popularity"]
df

0        96
1        77
2        92
3        93
4        88
         ..
39995    87
39996    93
39997    95
39998    95
39999    90
Name: popularity, Length: 39836, dtype: int64

In [370]:
# data type
df.dtype

dtype('int64')

In [371]:
# Statistical summary
df.describe()

count    39836.000000
mean        89.615248
std         10.041978
min          0.000000
25%         87.000000
50%         91.000000
75%         95.000000
max        100.000000
Name: popularity, dtype: float64

In [372]:
# Converting to Numeric
df = pd.to_numeric(df, errors='coerce')

In [373]:
# null value
df.isnull().sum()

np.int64(0)

In [374]:
data["popularity"] = df

C:\Users\sidha\AppData\Local\Temp\ipykernel_10848\322145060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["popularity"] = df

In [375]:
# value more or less ranges
data[data["popularity"]>100]

Empty DataFrame
Columns: [date, position, song, artist, popularity, duration_ms, album_type, total_tracks, release_date, is_explicit, album_cover_url, link, genre]
Index: []

In [376]:
# value less than ranges
data[data["popularity"]<0]

Empty DataFrame
Columns: [date, position, song, artist, popularity, duration_ms, album_type, total_tracks, release_date, is_explicit, album_cover_url, link, genre]
Index: []

In [377]:
# all done

# duration_ms

In [378]:
df = data["duration_ms"]
df

0        219724
1        259079
2        167303
3        261922
4        177440
          ...
39995    270295
39996    172797
39997    184066
39998    178030
39999    156345
Name: duration_ms, Length: 39836, dtype: int64

In [379]:
# data type
df.dtype

dtype('int64')

In [380]:
# null value
df.isnull().sum()

np.int64(0)

In [381]:
# less a min
df[df<=6000]

Series([], Name: duration_ms, dtype: int64)

In [382]:
data.loc[:, "duration_ms"] = df

In [383]:
# all done

# album_type

In [384]:
df = data["album_type"]
df

0         album
1         album
2         album
3         album
4        single
          ...
39995     Album
39996     album
39997    single
39998     album
39999    single
Name: album_type, Length: 39836, dtype: object

In [385]:
# data type
df.dtype

dtype('O')

In [386]:
# null value
df.isnull().sum()

np.int64(0)

In [387]:
# Removing extra space
df = data['album_type'].str.strip()

In [388]:
# converting into lower case
df = df.str.lower()

In [389]:
df

0         album
1         album
2         album
3         album
4        single
          ...
39995     album
39996     album
39997    single
39998     album
39999    single
Name: album_type, Length: 39836, dtype: object

In [390]:
# get category 
df.unique()

array(['album', 'single', 'compilation'], dtype=object)

In [391]:
# not in valid category
valid_album_types = ["album", "single", "compilation"]

In [392]:
invalid_rows = df[~df.isin(valid_album_types)]
invalid_rows

Series([], Name: album_type, dtype: object)

In [393]:
data.loc[:, "album_type"] = df

In [394]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,hiphop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-12-27,2,Last Christmas - Single Version,Wham!,87,270295,album,16,2023-07-07,False,NaN,https://open.spotify.com/search/Last%20Christm...,other
39996,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,other
39997,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,other
39998,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,other
39999,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,other

In [395]:
# all done

# total_track

In [396]:
df = data["total_tracks"]
df

0        12
1        26
2        13
3        16
4         2
         ..
39995    16
39996     9
39997     1
39998    23
39999     1
Name: total_tracks, Length: 39836, dtype: int64

In [397]:
# mathematical summary
df.describe()

count    39836.000000
mean        10.124837
std          8.320060
min          1.000000
25%          1.000000
50%         11.000000
75%         15.000000
max        119.000000
Name: total_tracks, dtype: float64

In [398]:
# null value
df.isnull().sum()

np.int64(0)

In [399]:
# find umrealistic value
df[df <= 0]

Series([], Name: total_tracks, dtype: int64)

In [400]:
# more than 100
data[df > 100]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
1781,2023-12-23,24,Hapyp Xmas (War Is Over) - Remastered 2010,John Lennon,89,215563,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
3525,2023-12-11,31,Happy Xmas (War Is Over) - Remastreed 2010,John Lennon,90,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
5032,2023-12-21,39,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
5685,2023-12-11,31,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,90,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
5972,2023-12-04,33,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,87,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
5995,2023-12-10,45,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,97,210658,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,NaN,other
6927,2023-12-20,42,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
8011,2023-12-27,15,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,209724,compilation,119,2010-10-05,False,NaN,https://open.spotify.com/search/Happy%20Xmas%2...,other
9179,2023-12-18,29,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
11434,2023-12-19,29,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,220218,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
12770,2023-12-19,26,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
15377,2023-12-17,29,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
15497,2023-12-19,22,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,86,214699,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
15892,2023-12-26,15,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
15994,2023-12-22,35,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
18415,2023-12-27,15,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
19407,2023-12-23,24,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
20711,2023-12-12,29,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,90,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
21343,2023-12-10,45,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,89,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
26395,2023-12-18,26,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,91,209217,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
27617,2023-12-11,31,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,86,212284,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
30201,2023-12-19,29,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,98,220415,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
35112,2023-12-03,37,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,86,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
35681,2023-12-25,14,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
38855,2023-12-24,15,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,92,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other
39915,2023-12-11,31,Happy Xmas (War Is Over) - Remastered 2010,John Lennon,90,214333,compilation,119,2010-10-05,False,https://i.scdn.co/image/ab67616d0000b27361a389...,https://open.spotify.com/search/Happy%20Xmas%2...,other

In [401]:
data.loc[:, "total_tracks"] = df

In [402]:
# remove that one artits
data = data[data["total_tracks"]<100]

In [403]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,hiphop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-12-27,2,Last Christmas - Single Version,Wham!,87,270295,album,16,2023-07-07,False,NaN,https://open.spotify.com/search/Last%20Christm...,other
39996,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,other
39997,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,other
39998,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,other
39999,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,other

In [404]:
# recheck
data[data["total_tracks"]>100]

Empty DataFrame
Columns: [date, position, song, artist, popularity, duration_ms, album_type, total_tracks, release_date, is_explicit, album_cover_url, link, genre]
Index: []

In [405]:
# all done

# release date

In [406]:
df = data["release_date"]
df

0        2023-09-08
1        2023-06-30
2        2022-05-20
3        2020-07-24
4        1978-11-27
            ...
39995    2023-07-07
39996    2023-08-10
39997    2023-01-23
39998    2023-09-18
39999    2023-08-17
Name: release_date, Length: 39810, dtype: object

In [407]:
# convering into date formate
df = pd.to_datetime(df, errors='coerce')

In [408]:
# null value 
df.isnull().sum()

np.int64(633)

In [409]:
data.loc[:, "release_date"] = df

In [410]:
data["release_date"].isnull().sum()

np.int64(633)

In [411]:
data[data["release_date"].isnull()]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
141,2024-08-05,17,I Had Some Help (Feat. Morgan Wallen),Post Malone & Morgan Wallen,95,178716,single,1,NaT,True,https://i.scdn.co/image/ab67616d0000b273973069...,https://open.spotify.com/search/I%20Had%20Some...,other
193,2024-09-08,42,Iris,The Goo Goo Dolls,88,289533,album,13,NaT,False,https://i.scdn.co/image/ab67616d0000b273eda947...,https://open.spotify.com/search/Iris%20The%20G...,other
200,2023-09-30,35,Die For You,The Weeknd,89,263589,album,18,NaT,False,https://i.scdn.co/image/ab67616d0000b273a04841...,https://open.spotify.com/search/Die%20For%20Yo...,other
267,2023-06-23,23,Los Del Espacio,Lit Killah,92,338000,single,1,NaT,False,https://i.scdn.co/image/ab67616d0000b27352c8b9...,https://open.spotify.com/search/Los%20del%20Es...,other
450,2023-08-25,1,Cruel Summer,Taylor Swift,100,174062,album,18,NaT,False,https://i.scdn.co/image/ab67616d0000b273e787cf...,https://open.spotify.com/search/Cruel%20Summer...,pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39657,2023-10-20,36,One Of Your Girls,Troye Sivan,77,182324,album,10,NaT,False,https://i.scdn.co/image/ab67616d0000b273671032...,https://open.spotify.com/search/One%20Of%20You...,other
39660,2024-08-09,32,I Wanna Be Yours,Arctic Monkeys,90,183956,album,12,NaT,False,https://i.scdn.co/image/ab67616d0000b2734ae1c4...,https://open.spotify.com/search/I%20Wanna%20Be...,other
39665,2023-06-10,32,Le Azul,Junior H & Peso Pluma,99,187563,single,1,NaT,False,https://i.scdn.co/image/ab67616d0000b27333ed35...,https://open.spotify.com/search/El%20Azul%20Ju...,other
39675,2024-08-01,31,I Wanna Be Yours,Arctic Monkeys,91,186428,album,12,NaT,False,https://i.scdn.co/image/ab67616d0000b2734ae1c4...,https://open.spotify.com/search/I%20Wanna%20Be...,other
39892,2023-09-14,44,Primera Cita,Carin Leon,86,183873,album,18,NaT,False,https://i.scdn.co/image/ab67616d0000b2730e30fc...,https://open.spotify.com/search/Primera%20Cita...,other

In [412]:
# removing null value
data = data.dropna(subset = ['release_date'])

In [413]:
data["release_date"].isnull().sum()

np.int64(0)

In [414]:
# datatype
data["release_date"].dtype

dtype('O')

In [415]:
# coverting data type
data["release_date"] = pd.to_datetime(data["release_date"], errors="coerce")

C:\Users\sidha\AppData\Local\Temp\ipykernel_10848\478406056.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["release_date"] = pd.to_datetime(data["release_date"], errors="coerce")

In [416]:
# datatype
data["release_date"].dtype

dtype('<M8[ns]')

In [417]:
# unfit released date ;- before  2023
data[data["release_date"]<"2023-01-01"].count()

# no need to remove  as old song also stand out

date               9120
position           9120
song               9120
artist             9120
popularity         9120
duration_ms        9120
album_type         9120
total_tracks       9120
release_date       9120
is_explicit        9120
album_cover_url    8891
link               9002
genre              9120
dtype: int64

In [418]:
# unfit released date :- aftere 2024
data[data["release_date"]>"2024-12-12"].count()

date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
release_date       0
is_explicit        0
album_cover_url    0
link               0
genre              0
dtype: int64

In [419]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,hiphop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-12-27,2,Last Christmas - Single Version,Wham!,87,270295,album,16,2023-07-07,False,NaN,https://open.spotify.com/search/Last%20Christm...,other
39996,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,other
39997,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,other
39998,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,other
39999,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,other

In [420]:
# all done

# is_explicit

In [421]:
df = data["is_explicit"]
df

0         True
1         True
2        False
3        False
4        False
         ...
39995    False
39996     True
39997     True
39998     True
39999     True
Name: is_explicit, Length: 39177, dtype: bool

In [422]:
df.unique()

array([ True, False])

In [423]:
df.isnull().sum()

np.int64(0)

In [424]:
# all done

# album_cover_url

In [425]:
df = data["album_cover_url"]
df

0        https://i.scdn.co/image/ab67616d0000b273e85259...
1        https://i.scdn.co/image/ab67616d0000b273a0e769...
2        https://i.scdn.co/image/ab67616d0000b2732e8ed7...
3        https://i.scdn.co/image/ab67616d0000b27395f754...
4        https://i.scdn.co/image/ab67616d0000b2736d4362...
                               ...
39995                                                  NaN
39996    https://i.scdn.co/image/ab67616d0000b273d026bf...
39997    https://i.scdn.co/image/ab67616d0000b2737be314...
39998    https://i.scdn.co/image/ab67616d0000b273c75c05...
39999    https://i.scdn.co/image/ab67616d0000b2730e8dc9...
Name: album_cover_url, Length: 39177, dtype: object

In [426]:
# data type
df.dtype

dtype('O')

In [427]:
df.isnull().sum()

np.int64(971)

In [428]:
# check ather rows
data[data["album_cover_url"].isnull()]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
27,2024-05-16,49,Si No Quieres No,Luis R Conriquez & Neton Vega,87,145945,single,1,2024-03-10,False,NaN,https://open.spotify.com/search/Si%20No%20Quie...,other
159,2024-09-10,38,Stargazing,Myles Smith,98,165814,single,1,2024-05-10,False,NaN,https://open.spotify.com/search/Stargazing%20M...,other
169,2024-07-03,16,Real Gangsta Love,Trueno,90,149236,album,13,2024-05-23,True,NaN,NaN,other
201,2023-12-24,21,Let It Snow! Let It Snow! Let It Snow! (With T...,Frank Sinatra,91,154871,album,14,1994-11-08,False,NaN,https://open.spotify.com/search/Let%20It%20Sno...,other
228,2024-10-01,46,Luna,Feid,88,191038,album,10,2023-12-01,False,NaN,https://open.spotify.com/search/LUNA%20Feid,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39828,2024-09-27,49,El Lokeron,Tito Double P,87,147531,album,21,2024-08-22,True,NaN,https://open.spotify.com/search/EL%20LOKERON%2...,other
39839,2024-06-03,2,Million Dollar Baby,Tommy Richman,98,150035,single,2,2024-04-26,False,NaN,https://open.spotify.com/search/MILLION%20DOLL...,other
39936,2024-05-13,38,Europapa,Joost,80,160118,single,2,2024-02-29,False,NaN,https://open.spotify.com/search/Europapa%20Joost,other
39993,2024-06-18,27,Austin (Boots Stop Workin'),Dasha,81,171782,album,8,2024-02-16,True,NaN,https://open.spotify.com/search/Austin%20%28Bo...,other
39995,2023-12-27,2,Last Christmas - Single Version,Wham!,87,270295,album,16,2023-07-07,False,NaN,https://open.spotify.com/search/Last%20Christm...,other

In [429]:
data[~data["album_cover_url"].isnull()]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,hiphop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39994,2023-07-08,34,I'M Good (Blue),David Guetta & Bebe Rexha,96,175238,single,2,2022-08-26,True,https://i.scdn.co/image/ab67616d0000b273933c03...,https://open.spotify.com/search/I%27m%20Good%2...,other
39996,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,other
39997,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,other
39998,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,other
39999,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,other

In [430]:
# mmodify data
data = data[~data["album_cover_url"].isnull()]

In [431]:
data["album_cover_url"].isnull().sum()

np.int64(0)

In [432]:
# how should check whether url is valid or not
data[~data['album_cover_url'].str.startswith('http', na=False)].count()

date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
release_date       0
is_explicit        0
album_cover_url    0
link               0
genre              0
dtype: int64

In [433]:
# still modify it
data = data[data['album_cover_url'].str.startswith('http', na=False)]

In [434]:
# removing spaces
data['album_cover_url'] = data['album_cover_url'].str.strip()

In [435]:
data['album_cover_url'].dtype

dtype('O')

In [436]:
# all done

# link

In [437]:
df = data["link"]
df

0        https://open.spotify.com/search/vampire%20Oliv...
1        https://open.spotify.com/search/Suicide%20Door...
2        https://open.spotify.com/search/As%20It%20Was%...
3        https://open.spotify.com/search/august%20Taylo...
4        https://open.spotify.com/search/Please%20Come%...
                               ...
39994    https://open.spotify.com/search/I%27m%20Good%2...
39996    https://open.spotify.com/search/QLONA%20KAROL%20G
39997    https://open.spotify.com/search/PRC%20Peso%20P...
39998    https://open.spotify.com/search/LA%20FALDA%20M...
39999    https://open.spotify.com/search/La%20V%C3%ADct...
Name: link, Length: 38206, dtype: object

In [438]:
df.isnull().sum()

np.int64(483)

In [439]:
# remove extra space
df = df.str.strip()

In [440]:
# modify data
data.loc[:, "link"] = df

In [444]:
# null value row
data[data["link"].isnull()]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
44,2024-04-09,20,Corazón De Piedra,Xavi,83,193568,single,1,2024-03-21,False,https://i.scdn.co/image/ab67616d0000b273572e68...,NaN,other
184,2024-01-15,33,All Of Me,21 Savage,84,195410,album,15,2024-01-12,True,https://i.scdn.co/image/ab67616d0000b273bbdceb...,NaN,hiphop
305,2024-08-18,8,A Bar Song (Tipsy),Shaboozey,84,177286,album,12,2024-05-31,True,https://i.scdn.co/image/ab67616d0000b27360df03...,NaN,other
380,2024-11-25,41,Locked Out Of Heaven,Bruno Mars,81,233784,album,10,2012-12-07,False,https://i.scdn.co/image/ab67616d0000b273926f43...,NaN,other
382,2024-10-14,48,End Of Beginning,Djo,86,159245,album,13,2022-09-16,False,https://i.scdn.co/image/ab67616d0000b273fddfff...,NaN,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39097,2023-06-14,43,Another Love,Tom Odell,91,244922,album,15,2013-06-24,True,https://i.scdn.co/image/ab67616d0000b2731917a0...,NaN,other
39149,2024-02-01,2,Greedy,Tate Mcrae,92,131872,single,1,2023-09-15,True,https://i.scdn.co/image/ab67616d0000b27322fd80...,NaN,other
39378,2023-09-07,7,Cruel Sumemr,Taylor Swift,100,178107,album,18,2019-08-23,False,https://i.scdn.co/image/ab67616d0000b273e787cf...,NaN,pop
39460,2024-01-08,5,"One Of The Girls (With Jennie, Lily Rose Depp)",The Weeknd & Jennie & Lily-Rose Depp,96,246645,single,3,2023-06-23,False,https://i.scdn.co/image/ab67616d0000b273b0dd6a...,NaN,hiphop
39639,2023-10-18,43,I Remember Everything (Feat. Kacey Musgraves),Zach Bryan,92,222993,album,16,2023-08-25,False,https://i.scdn.co/image/ab67616d0000b273e5a25e...,NaN,other

In [447]:
# modify data 
data = data[~data["link"].isnull()]

In [448]:
# all done

# genre

In [449]:
df = data["genre"]
df

0         other
1        hiphop
2         other
3           pop
4         other
          ...
39994     other
39996     other
39997     other
39998     other
39999     other
Name: genre, Length: 37723, dtype: object

In [450]:
# finding unique value
df.unique()

array(['other', 'hiphop', 'pop', ' other ', ' hiphop ', 'classic',
       ' pop ', ' classic '], dtype=object)

In [451]:
# removing ecxtra space
df = df.str.strip()

In [452]:
# again finding unique value
df.unique()

array(['other', 'hiphop', 'pop', 'classic'], dtype=object)

In [454]:
# null value 
df.isnull().sum()

np.int64(0)

In [455]:
# replace hiphop = hip-hop
df = df.replace({
    'hiphop': 'hip-hop'
})

In [457]:
# Tittle format
df = df.str.title()

In [458]:
# again finding unique value
df.unique()

array(['Other', 'Hip-Hop', 'Pop', 'Classic'], dtype=object)

In [460]:
data.loc[:,"genre"] = df

In [463]:
# all done

# overall columns

In [471]:
data.duplicated().sum()

np.int64(496)

In [475]:
data[data.duplicated()]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
389,2024-07-14,39,The Night We Met,Lord Huron,89,208211,album,14,2015-04-06,False,https://i.scdn.co/image/ab67616d0000b27317875a...,https://open.spotify.com/search/The%20Night%20...,Other
597,2024-10-06,1,Die With A Smile,Lady Gaga & Bruno Mars,100,251667,single,1,2024-08-16,False,https://i.scdn.co/image/ab67616d0000b27382ea2e...,https://open.spotify.com/search/Die%20With%20A...,Other
2180,2023-08-06,21,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,Other
2647,2024-01-16,36,Daylight,David Kushner,95,212953,single,1,2023-04-14,False,https://i.scdn.co/image/ab67616d0000b27395ca6a...,https://open.spotify.com/search/Daylight%20Dav...,Other
3628,2023-11-05,48,Columbia,Quevedo,95,186000,single,1,2023-07-07,False,https://i.scdn.co/image/ab67616d0000b273a00a81...,https://open.spotify.com/search/Columbia%20Que...,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37537,2024-09-11,16,Guess Featuring Billie Eilish,Charli Xcx & Billie Eilish,92,143330,single,1,2024-08-01,False,https://i.scdn.co/image/ab67616d0000b2738b8d8b...,https://open.spotify.com/search/Guess%20featur...,Other
37574,2024-08-14,40,Chihiro,Billie Eilish,92,303440,album,10,2024-05-17,False,https://i.scdn.co/image/ab67616d0000b27371d62e...,https://open.spotify.com/search/CHIHIRO%20Bill...,Other
37598,2023-09-19,30,Primera Cita,Carin Leon,85,186455,album,18,2023-05-19,False,https://i.scdn.co/image/ab67616d0000b2730e30fc...,https://open.spotify.com/search/Primera%20Cita...,Other
37612,2023-07-09,1,Mine (Taylor'S Version),Taylor Swift,0,231706,album,22,2023-07-07,False,https://i.scdn.co/image/ab67616d0000b2730b04da...,https://open.spotify.com/search/Mine%20%28Tayl...,Pop
37640,2024-05-24,33,Austin,Dasha,92,171782,album,8,2024-02-16,True,https://i.scdn.co/image/ab67616d0000b2734ccf88...,https://open.spotify.com/search/Austin%20Dasha,Other

In [476]:
data[data.duplicated()].count()

date               496
position           496
song               496
artist             496
popularity         496
duration_ms        496
album_type         496
total_tracks       496
release_date       496
is_explicit        496
album_cover_url    496
link               496
genre              496
dtype: int64

In [477]:
data = data[~data.duplicated()]

In [482]:
data.duplicated().sum()

np.int64(0)

In [483]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,Other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,Hip-Hop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,Other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,Pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37718,2023-07-08,34,I'M Good (Blue),David Guetta & Bebe Rexha,96,175238,single,2,2022-08-26,True,https://i.scdn.co/image/ab67616d0000b273933c03...,https://open.spotify.com/search/I%27m%20Good%2...,Other
37719,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,Other
37720,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,Other
37721,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,Other
37722,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,Other

In [484]:
# all done

# Exporting

In [485]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,Other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,Hip-Hop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,Other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,Pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37718,2023-07-08,34,I'M Good (Blue),David Guetta & Bebe Rexha,96,175238,single,2,2022-08-26,True,https://i.scdn.co/image/ab67616d0000b273933c03...,https://open.spotify.com/search/I%27m%20Good%2...,Other
37719,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,Other
37720,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,Other
37721,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,Other
37722,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,Other

In [486]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37227 entries, 0 to 37722
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             37227 non-null  datetime64[ns]
 1   position         37227 non-null  int64
 2   song             37227 non-null  object
 3   artist           37227 non-null  object
 4   popularity       37227 non-null  int64
 5   duration_ms      37227 non-null  int64
 6   album_type       37227 non-null  object
 7   total_tracks     37227 non-null  int64
 8   release_date     37227 non-null  datetime64[ns]
 9   is_explicit      37227 non-null  bool
 10  album_cover_url  37227 non-null  object
 11  link             37227 non-null  object
 12  genre            37227 non-null  object
dtypes: bool(1), datetime64[ns](2), int64(4), object(6)
memory usage: 3.7+ MB

In [487]:
data = data.reset_index(drop=True)

In [488]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url,link,genre
0,2023-10-18,20,Vampire,Olivia Rodrigo,96,219724,album,12,2023-09-08,True,https://i.scdn.co/image/ab67616d0000b273e85259...,https://open.spotify.com/search/vampire%20Oliv...,Other
1,2023-07-02,12,Suicide Doors,Lil Uzi Vert,77,259079,album,26,2023-06-30,True,https://i.scdn.co/image/ab67616d0000b273a0e769...,https://open.spotify.com/search/Suicide%20Door...,Hip-Hop
2,2024-07-04,22,As It Was,Harry Styles,92,167303,album,13,2022-05-20,False,https://i.scdn.co/image/ab67616d0000b2732e8ed7...,https://open.spotify.com/search/As%20It%20Was%...,Other
3,2023-09-03,27,August,Taylor Swift,93,261922,album,16,2020-07-24,False,https://i.scdn.co/image/ab67616d0000b27395f754...,https://open.spotify.com/search/august%20Taylo...,Pop
4,2023-12-26,31,Please Come Home For Christmas - 2013 Remaster,Eagles,88,177440,single,2,1978-11-27,False,https://i.scdn.co/image/ab67616d0000b2736d4362...,https://open.spotify.com/search/Please%20Come%...,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37222,2023-07-08,34,I'M Good (Blue),David Guetta & Bebe Rexha,96,175238,single,2,2022-08-26,True,https://i.scdn.co/image/ab67616d0000b273933c03...,https://open.spotify.com/search/I%27m%20Good%2...,Other
37223,2024-02-20,28,Qlona,Karol G,93,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,https://open.spotify.com/search/QLONA%20KAROL%20G,Other
37224,2023-06-05,20,Prc,Peso Pluma & Natanael Cano,95,184066,single,1,2023-01-23,True,https://i.scdn.co/image/ab67616d0000b2737be314...,https://open.spotify.com/search/PRC%20Peso%20P...,Other
37225,2024-02-17,26,La Falda,Myke Towers,95,178030,album,23,2023-09-18,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,https://open.spotify.com/search/LA%20FALDA%20M...,Other
37226,2023-12-18,43,La Víctima,Xavi,90,156345,single,1,2023-08-17,True,https://i.scdn.co/image/ab67616d0000b2730e8dc9...,https://open.spotify.com/search/La%20V%C3%ADct...,Other

In [489]:
data.to_csv("cleaned_spotify.csv", index=False)